### <font color="brown">NumPy - Continued</font>

In [4]:
import numpy as np

---

**The max function is not a ufunc (universal function - the second parameter is a scalar that refers to the "axis"**

In [2]:
arr3 = [3,5,1,15,7]
print(arr3)

[3, 5, 1, 15, 7]


In [5]:
np.max(arr3,0)  # max is not binary unfunc, second arg for max is "axis"

15

**The binary ufunc name (maximum) is different from unary ufunc name (max) because the 2nd argument has a different meaning from one to the other**

In [6]:
arr2d = np.arange(1,10).reshape(3,3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
print(np.max(arr2d, 1))  # maximums for each of the rows (across columns), dimension argument is 1

[3 6 9]


In [9]:
print(np.max(arr2d, 0))  # maximums for each of the columns (down rows), dimension argument is 0

[7 8 9]


In [11]:
arr = np.array([1,2,np.nan,4,5])
arr

array([ 1.,  2., nan,  4.,  5.])

**fmax is a universal function (ufunc) that works like maximum, difference is it ignores NaN**

In [17]:
print(arr3)
print(arr)

[3, 5, 1, 15, 7]
[ 1.  2. nan  4.  5.]


In [18]:
np.maximum(arr3,arr)

array([ 3.,  5., nan, 15.,  7.])

In [19]:
np.fmax(arr3,arr)   

array([ 3.,  5.,  1., 15.,  7.])

**greater ufunc**

In [21]:
arr1 = [1,2,3,4]
arr2 = [2,1,2,3]
np.greater(arr1,arr2)  

array([False,  True,  True,  True])

---

#### <font color="brown">Using NumPy random module</font>

**randint function**

In [25]:
np.random.randint(-50,0)  
# single random integer between -50 (inclusive) and 0 (exclusive)

-19

In [26]:
# same as basic Python random.randint except in basic Python random.randint, 2nd arg is inclusive
import random
random.randint(-50,0)

-43

In [27]:
np.random.randint(1,100,5)  
# 5 random integers between 1 (inclusive) and 100 (exclusive)

array([30, 89, 49, 88, 59])

In [28]:
np.random.randint(1,100,(2,3))  
# fill (2,3) array with random integers in range 1..99

array([[60, 77, 65],
       [60, 51, 47]])

**random function**

In [29]:
np.random.random(5)  # 5 random reals 0 (inclusive) thru 1 (exclusive)

array([0.36726299, 0.4402782 , 0.70520181, 0.29861085, 0.75798912])

In [30]:
# basic Python version returns a single random number in the range [0,1)
random.random()

0.8328581900150154

In [6]:
np.random.random((3,2)) * 5

array([[0.43281017, 0.47194877],
       [4.06853405, 1.5228225 ],
       [4.98113823, 1.36361611]])

**choice function**

In [33]:
nlst = [1,5,3,2,19,12,22,18,75,2,-10,0,15]
np.random.choice(nlst,3)  # 3 random selections from nlst

array([-10, -10,  22])

In [34]:
# Python random.choice gives a single item
random.choice(nlst)  

15

In [35]:
np.random.choice(nlst,8)  

array([ 3,  3,  1,  1, 19, 18,  5,  3])

In [36]:
np.random.choice(nlst,size=8,replace=False)   # no duplicates

array([ 19, -10,  12,  18,   0,   1,   2,   5])

**shuffle function**

In [37]:
arrs = np.arange(1,10)
arrs

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.random.shuffle(arrs)
arrs

array([2, 6, 9, 1, 8, 3, 5, 7, 4])

**<font color="red">Note: shuffle changes the original array</font>**

In [39]:
arrs2d = np.random.randint(1,50,(3,4))
arrs2d

array([[27,  9, 32, 30],
       [19,  9,  9, 12],
       [28, 42, 45, 47]])

In [41]:
np.random.shuffle(arrs2d)  # only shuffles rows 
arrs2d

array([[19,  9,  9, 12],
       [27,  9, 32, 30],
       [28, 42, 45, 47]])

**<font color="red">shuffle only shuffles the rows (in general, only shuffles 1st axis of a multidimensional array)</font>**

In [45]:
arr3d = np.arange(18).reshape(3,3,2)
print(arr3d)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]


In [46]:
np.random.shuffle(arr3d)
arr3d

array([[[12, 13],
        [14, 15],
        [16, 17]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[ 0,  1],
        [ 2,  3],
        [ 4,  5]]])

**permutation function**

In [48]:
arrp = np.arange(1,10)
np.random.permutation(arrp)

array([6, 2, 3, 5, 7, 8, 9, 4, 1])

In [49]:
arrp

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

**<font color="red">Note that permutation does NOT change the original array</font>**

In [52]:
arrp2d = np.random.randint(1,50,(5,3))
arrp2d

array([[20, 13, 33],
       [11, 21, 48],
       [13, 48, 14],
       [41, 33, 13],
       [29, 32,  8]])

In [53]:
np.random.permutation(arrp2d)  # only permutes rows

array([[13, 48, 14],
       [20, 13, 33],
       [29, 32,  8],
       [11, 21, 48],
       [41, 33, 13]])

**<font color="red">Like shuffle, permutation only permutes the rows (in general, only permutes 1st axis of a multidimensional array)</font>**

In [54]:
arrp2d  # original not changed

array([[20, 13, 33],
       [11, 21, 48],
       [13, 48, 14],
       [41, 33, 13],
       [29, 32,  8]])

---

#### <font color="brown">NumPy math and stats functions ("reductions")</font>
**functions min, max, mean, sum, std, cumsum**

In [11]:
arrx = np.random.randint(1,20,5)
print(arrx)
print(arrx.max())  
print(arrx.min())
print(arrx.mean())
print(arrx.sum())
print(arrx.std())
print(arrx.cumsum())

[ 3 16 14  8 12]
16
3
10.6
53
4.6303347611160905
[ 3 19 33 41 53]


In [10]:
# Alternatively, can use same-named np functions instead of ndarray methods
print(arrx)
print(np.max(arrx))  
print(np.min(arrx))
print(np.mean(arrx))
print(np.sum(arrx))
print(np.std(arrx))
print(np.cumsum(arrx))

[ 2 17  4  9 12]
17
2
8.8
44
5.418486873657627
[ 2 19 23 32 44]


**functions argmax, argmin**

In [60]:
narr = np.array([3,1,-10,5,2,0,-10])
narr

array([  3,   1, -10,   5,   2,   0, -10])

In [62]:
# index of minimum value
print(narr.argmin())  # ndarray method
print(np.argmin(narr))  # np function

2
2


**<font color="red">Using axis for reductions on rows only or columns only</font>**

In [66]:
arr2d = np.arange(1,10).reshape(3,3)[[1,0,2]][:,[1,2,0]]
arr2d

array([[5, 6, 4],
       [2, 3, 1],
       [8, 9, 7]])

In [71]:
# ndarray method versions
print('max in each column: ',end='')
print(arr2d.max(axis=0))
print('row index of max in each column: ',end='')
print(arr2d.argmax(axis=0))
print('max in each row: ',end='')
print(arr2d.max(axis=1))
print('column index of max in each row: ',end='')
print(arr2d.argmax(axis=1))
print()
print('min in each column: ',end='')
print(arr2d.min(axis=0))
print('row index of min in each column: ',end='')
print(arr2d.argmin(axis=0))
print('min in each row: ',end='')
print(arr2d.min(axis=1))
print('column index of min in each row: ',end='')
print(arr2d.argmin(axis=1))

max in each column: [8 9 7]
row index of max in each column: [2 2 2]
max in each row: [6 3 9]
column index of max in each row: [1 1 1]

min in each column: [2 3 1]
row index of min in each column: [1 1 1]
min in each row: [4 1 7]
column index of min in each row: [2 2 2]


In [72]:
# np function versions
print('max in each column: ',end='')
print(np.max(arr2d,axis=0))
print('row index of max in each column: ',end='')
print(np.argmax(arr2d,axis=0))
print('max in each row: ',end='')
print(np.max(arr2d,axis=1))
print('column index of max in each row: ',end='')
print(np.argmax(arr2d,axis=1))

max in each column: [8 9 7]
row index of max in each column: [2 2 2]
max in each row: [6 3 9]
column index of max in each row: [1 1 1]


**<font color="red">Without axis argument, functions apply to entire 2d array<font>**

In [75]:
arr2d

array([[5, 6, 4],
       [2, 3, 1],
       [8, 9, 7]])

In [76]:
arr2d.mean()

5.0

In [77]:
arr2d.mean(axis=1)  # mean of column values for each row

array([5., 2., 8.])

In [78]:
arr2d.mean(axis=0)  # mean of row values for each column

array([5., 6., 4.])

In [79]:
arr2d.cumsum(axis=0)  # cumulative sum for each column

array([[ 5,  6,  4],
       [ 7,  9,  5],
       [15, 18, 12]])

---

#### <font color="brown">Unique</font>

In [80]:
scores = np.array([10,9,9,8,2,3,2,7,5,8])
np.unique(scores)   

array([ 2,  3,  5,  7,  8,  9, 10])

**Gives <font color="red">sorted</font> list of unique values**

In [90]:
arr = [[ 3,  3,  9],
       [10, 12,  1],
       [ 9,  8,  4],
       [ 2,  3, 12]]

In [94]:
np.unique(arr)

array([ 1,  2,  3,  4,  8,  9, 10, 12])

---

#### <font color="brown">Sorting</font>

In [98]:
a = np.array([3,-1,2,5,15,22,-10,85])
print(a)

[  3  -1   2   5  15  22 -10  85]


**np sort function**

In [99]:
np.sort(a)

array([-10,  -1,   2,   3,   5,  15,  22,  85])

In [100]:
print(a) 

[  3  -1   2   5  15  22 -10  85]


**<font color="red">Note that sort function does not change the original array</font>**

**ndarray sort method**

In [101]:
a.sort()  
print(a)

[-10  -1   2   3   5  15  22  85]


**<font color="red">Note that ndarray sort method changes the original array</font>**

In [102]:
a = np.array([3,-1,2,5,15,22,-10,85])
print(a)

[  3  -1   2   5  15  22 -10  85]


**np argsort function**

In [109]:
# positions of sorted values
sort_ix = np.argsort(a)
print(np.sort(a))
print(sort_ix)

[-10  -1   2   3   5  15  22  85]
[6 1 2 0 3 4 5 7]


**ndarray argsort method**

In [107]:
print(a.argsort())

[6 1 2 0 3 4 5 7]


**sort on 2D array**

In [110]:
a = [3,-1,2,5,15,22,-10,85]
b = [9,2,15,10,1,3,-2,5]
c = np.array([a,b])
print(c)

[[  3  -1   2   5  15  22 -10  85]
 [  9   2  15  10   1   3  -2   5]]


In [116]:
np.sort(c)

array([[-10,  -1,   2,   3,   5,  15,  22,  85],
       [ -2,   1,   2,   3,   5,   9,  10,  15]])

**<font color="red">Note that each row is individually sorted</font>**

In [111]:
np.argsort(c)  

array([[6, 1, 2, 0, 3, 4, 5, 7],
       [6, 4, 1, 5, 7, 0, 3, 2]])

In [112]:
np.argsort(c)[:,-3:]  # positions of max 3 values in each row

array([[4, 5, 7],
       [0, 3, 2]])

In [113]:
arr = np.random.randint(1,13,(4,3))
print(arr)

[[ 6 12  3]
 [ 2  4 10]
 [ 1  9  6]
 [10  4  7]]


In [114]:
np.sort(arr,axis=0)   # sort along columns

array([[ 1,  4,  3],
       [ 2,  4,  6],
       [ 6,  9,  7],
       [10, 12, 10]])

In [115]:
np.argsort(arr,axis=0)

array([[2, 1, 0],
       [1, 3, 2],
       [0, 2, 3],
       [3, 0, 1]])

In [116]:
np.sort(arr,axis=1)  # sort each row

array([[ 3,  6, 12],
       [ 2,  4, 10],
       [ 1,  6,  9],
       [ 4,  7, 10]])

In [117]:
np.sort(arr)  # axis=1 is default

array([[ 3,  6, 12],
       [ 2,  4, 10],
       [ 1,  6,  9],
       [ 4,  7, 10]])

---

#### <font color="brown">where function</font>

In [118]:
xlst = [1,2,3,4,5]
ylst = [6,7,8,9,10]
condlst = [True, False, True, True, False]

In [119]:
# want value from xarr if cond is True, otherwise value from yarr
res = [x if c else y
           for x,y,c in zip(xlst, ylst, condlst)]
res

[1, 7, 3, 4, 10]

**Using where function to conditionally manipulate items of array**

In [121]:
# above list comprehension is equivalent to this
np.where(condlst, xlst, ylst)

array([ 1,  7,  3,  4, 10])

**Either or both of 2nd and 3rd arguments to np.where can be scalars**

In [122]:
arr = np.random.randint(-5,5,(4,4))
print(arr,'\n')

# replace all negative values with -1 and other values with 1
arrx = np.where(arr < 0, -1, 1)
print(arrx)

[[-4 -2  0  3]
 [ 1  0 -1  2]
 [-3 -5 -5 -1]
 [-2  0  3  3]] 

[[-1 -1  1  1]
 [ 1  1 -1  1]
 [-1 -1 -1 -1]
 [-1  1  1  1]]


In [123]:
# replace only negative values with -1
arrx = np.where(arr < 0, -1, arr)
print(arrx)

[[-1 -1  0  3]
 [ 1  0 -1  2]
 [-1 -1 -1 -1]
 [-1  0  3  3]]


---

#### <font color="brown">Boolean arrays</font>
**Boolean values are coerced to 1 (True) and 0 (False)**

##### Exercise: Find number of positive values in an array

In [124]:
arr = np.array([1,-5,2,3,-4,6])
arr > 0

array([ True, False,  True,  True, False,  True])

In [125]:
(arr > 0).sum()    # number of True values 

4

In [126]:
print((arr > 0).any())
print((arr > 0).all())

True
False


---

#### <font color="brown">Linear Algebra</font>

In [127]:
narr = np.arange(0,32).reshape(4,8)
narr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

**Matrix Transpose**

In [128]:
narr.T  # transpose, rows become columns and vice versa

array([[ 0,  8, 16, 24],
       [ 1,  9, 17, 25],
       [ 2, 10, 18, 26],
       [ 3, 11, 19, 27],
       [ 4, 12, 20, 28],
       [ 5, 13, 21, 29],
       [ 6, 14, 22, 30],
       [ 7, 15, 23, 31]])

In [129]:
# alternatively
narr.transpose()  

array([[ 0,  8, 16, 24],
       [ 1,  9, 17, 25],
       [ 2, 10, 18, 26],
       [ 3, 11, 19, 27],
       [ 4, 12, 20, 28],
       [ 5, 13, 21, 29],
       [ 6, 14, 22, 30],
       [ 7, 15, 23, 31]])

In [130]:
narr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

**<font color="red">Note that transpose does not change the original array</font>**

**np function version**

In [131]:
np.transpose(narr)

array([[ 0,  8, 16, 24],
       [ 1,  9, 17, 25],
       [ 2, 10, 18, 26],
       [ 3, 11, 19, 27],
       [ 4, 12, 20, 28],
       [ 5, 13, 21, 29],
       [ 6, 14, 22, 30],
       [ 7, 15, 23, 31]])

In [132]:
narr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

**Matrix Multiplication**

In [133]:
mat1 = np.arange(1,7).reshape(2,3)
mat1

array([[1, 2, 3],
       [4, 5, 6]])

In [134]:
mat2 = np.arange(1,7).reshape(3,2)
mat2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [135]:
np.dot(mat1,mat2)  # matrix multiply mat1 with mat2

array([[22, 28],
       [49, 64]])

In [136]:
mat2, mat1

(array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [88]:
np.dot(mat2,mat1)  # matrix multiply mat2 with mat1

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [137]:
mat3 = np.array([-1,1,3,2,2,4]).reshape(2,3)
mat3

array([[-1,  1,  3],
       [ 2,  2,  4]])

In [138]:
mat1.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [139]:
np.dot(mat1.T,mat3)  # transpose mat1, then matrix multiply with mat3

array([[ 7,  9, 19],
       [ 8, 12, 26],
       [ 9, 15, 33]])

In [141]:
np.dot(np.array([1,2,3]), np.array([1,2,3]))  # dot product of two vectors

14