### <font color="brown">NumPy - Continued</font>

In [1]:
import numpy as np

---

#### <font color="brown">Type Casting</font>

##### You can CAST an array from one dtype to another using astype method.<br>Using astype ALWAYS CREATES A NEW ARRAY, leaving the original array untouched

In [3]:
floatarr = np.array([1,2.5,3])
floatarr.dtype

dtype('float64')

In [4]:
intarr = floatarr.astype(np.int64)
intarr, intarr.dtype

(array([1, 2, 3]), dtype('int64'))

In [5]:
# or, can just say int instead of np.int64
intarr2 = floatarr.astype(int)
intarr2, intarr2.dtype

(array([1, 2, 3]), dtype('int64'))

**Can parse strings that represent numeric values into numeric type**

In [6]:
num_strings = np.array(['1.5', '3.6', '-2.9'])
narr = num_strings.astype(float)  # parse each item as a real number
narr, narr.dtype

(array([ 1.5,  3.6, -2.9]), dtype('float64'))

**Only if the string actually does represent a numeric value**

In [7]:
np.array(['1.2','2.5','x.y']).astype(float)

ValueError: could not convert string to float: 'x.y'

In [8]:
# assign another array's dtype to intarr
farr = intarr.astype(floatarr.dtype) 
farr, intarr

(array([1., 2., 3.]), array([1, 2, 3]))

---

#### <font color="brown">Array-array and array-scalar operations</font>

##### Batch operations applied to arrays as a whole is called <em>vectorization</em>

In [9]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
arr * arr # corresponding elements are multiplied

array([[ 1,  4,  9],
       [16, 25, 36]])

In [11]:
arr + arr  # corresponding elements are added

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [12]:
1/arr  # invert each element

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [13]:
arr ** 2  # square each element

array([[ 1,  4,  9],
       [16, 25, 36]])

In [14]:
np.power(arr,2)

array([[ 1,  4,  9],
       [16, 25, 36]])

---

#### <font color="brown">Indexing and Slicing</font>

#### 1D Array

In [18]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arr[5:8]

array([5, 6, 7])

In [25]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [26]:
arr[:-2]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [27]:
arr[-3:]

array([7, 8, 9])

In [28]:
arr[3:-5]

array([3, 4])

**<font color="red">A slice on a 1D array is a "view" (not copy) on original array. If you modify a slice, the original array is modified!!</font>**

In [19]:
arr_slice = arr[5:8]
arr_slice

array([5, 6, 7])

In [20]:
arr_slice[1] = 66  
arr  

array([ 0,  1,  2,  3,  4,  5, 66,  7,  8,  9])

**Modification to the slice reflects in the original!**

In [21]:
arr[5:8][1] = 6  # 2nd element of the slice
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr[5:8] = 10  # every slice item is set to 10
arr

array([ 0,  1,  2,  3,  4, 10, 10, 10,  8,  9])

In [75]:
# remember, arr_slice is a view on the original, so it reflects change as well
arr_slice  

array([10, 10, 10])

In [23]:
arr_slice[:] = 13 # every slice item is set to 13
arr

array([ 0,  1,  2,  3,  4, 13, 13, 13,  8,  9])

**You can make a copy of a slice by using copy method**

In [24]:
slice_copy = arr[5:8].copy()  # explicit copy of slice, not a view
slice_copy[1] = 66
print(arr)
print(slice_copy)

[ 0  1  2  3  4 13 13 13  8  9]
[13 66 13]


---

#### 2D Array

In [25]:
myarr = np.arange(1,10).reshape(3,3)
myarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
myarr[1]  # second row

array([4, 5, 6])

In [ ]:
myarr[:,2]  # third column

array([3, 6, 9])

In [60]:
# 1st and 3rd rows
myarr[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [61]:
# can also be written like this
myarr[[-3,-1]]

array([[1, 2, 3],
       [7, 8, 9]])

In [52]:
# 1st and 3rd columns
myarr[:,[0,2]]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [64]:
myarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
# shuffle rows
myarr[[2,0,1]]

array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

In [66]:
# shuffle columns
myarr[:,[2,0,1]]

array([[3, 1, 2],
       [6, 4, 5],
       [9, 7, 8]])

In [53]:
myarr[1] = [-1,-2,-3]  # update 2nd row
myarr

array([[ 1,  2,  3],
       [-1, -2, -3],
       [ 7,  8,  9]])

In [54]:
myarr[:,2] = [2,1,0]   # update 3rd column
myarr

array([[ 1,  2,  2],
       [-1, -2,  1],
       [ 7,  8,  0]])

In [55]:
myarr[:,2] = -1   # set all items of 3rd column to same value
myarr

array([[ 1,  2, -1],
       [-1, -2, -1],
       [ 7,  8, -1]])

**Row and columns index lists**

In [66]:
narr = np.arange(32).reshape(8,4)
narr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [67]:
narr[[2,4,0,7],[1,2,0,3]]  # selects [2,1],[4,2],[0,0],[7,3]

array([ 9, 18,  0, 31])

In [68]:
narr[[2,4,0,7]]  # rows as specified

array([[ 8,  9, 10, 11],
       [16, 17, 18, 19],
       [ 0,  1,  2,  3],
       [28, 29, 30, 31]])

In [69]:
narr[[2,4,0,7]][:,[1,2,3,0]]  # shuffle columns

array([[ 9, 10, 11,  8],
       [17, 18, 19, 16],
       [ 1,  2,  3,  0],
       [29, 30, 31, 28]])

In [70]:
# above is equivalent to
narr_subrows = narr[[2,4,0,7]]
print(narr_subrows,'\n')
narr_subrows_shuffle = narr_subrows[:,[1,2,3,0]]
print(narr_subrows_shuffle)

[[ 8  9 10 11]
 [16 17 18 19]
 [ 0  1  2  3]
 [28 29 30 31]] 

[[ 9 10 11  8]
 [17 18 19 16]
 [ 1  2  3  0]
 [29 30 31 28]]


**Modifying row slice**

In [67]:
arr2d = np.arange(1,10).reshape(3,3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
rowslc = arr2d[1:]
rowslc

array([[4, 5, 6],
       [7, 8, 9]])

In [69]:
rowslc[0] = 10
rowslc

array([[10, 10, 10],
       [ 7,  8,  9]])

In [70]:
arr2d  # original array is modified!

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

**<font color="red">Above shows that slicing by row gives a VIEW, not a copy</font>**

**Modifying column slice**

In [72]:
arr2d = np.arange(1,10).reshape(3,3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
colslc = arr2d[:, [0,2]]  # 1st and 3rd columns
colslc

array([[1, 3],
       [4, 6],
       [7, 9]])

In [74]:
colslc[:,1] = 10  # assign 10 to second column of slice
colslc

array([[ 1, 10],
       [ 4, 10],
       [ 7, 10]])

In [75]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**<font color="red">Above shows that slicing by column gives a COPY, not a view**

---

#### <font color="brown">Slicing using a boolean filter (mask)</font>

In [82]:
arr=np.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [83]:
slc = arr[arr > 4]  # pick elements > 4
slc

array([5, 6, 7, 8])

In [84]:
# basically what you are doing is making a boolean filter array, then applying it on arr
filter = arr > 4
filter

array([False, False, False, False, False,  True,  True,  True,  True])

In [85]:
slc = arr[filter]
slc

array([5, 6, 7, 8])

In [86]:
slc[0] = 10
slc

array([10,  6,  7,  8])

In [87]:
arr  # original is not modified

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

**<font color="red">Slicing with boolean filtering gives a COPY, not a view</font>**

In [29]:
arr2d = np.arange(1,13).reshape(4,3)
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [30]:
arr2d_slc = arr2d[[True,False,True,True]] # get all but 2nd row
print(arr2d_slc)

[[ 1  2  3]
 [ 7  8  9]
 [10 11 12]]


In [31]:
arr2d_slc[0] = 0  # change 1st row to all zeros
arr2d_slc

array([[ 0,  0,  0],
       [ 7,  8,  9],
       [10, 11, 12]])

In [32]:
arr2d   # unchanged

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [33]:
arr2d[[i%2 == 0 for i in range(4)]]  # even indexed rows

array([[1, 2, 3],
       [7, 8, 9]])

**Applying a boolean mask from one array to another**

In [40]:
numarr = np.array([2,5,4,12])
arr2d[(numarr % 2 == 0)]   # basically arr2d[[True,False,True,True]]

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [10, 11, 12]])

In [37]:
arr2d[~(numarr % 2 == 0)]  # negation, gets only the 2nd row of arr2d

array([[4, 5, 6]])

In [95]:
arr2d[(numarr % 2 == 0),0]  # only the 1st column of selected rows

array([ 1,  7, 10])

In [96]:
mask = (numarr < 3) | (numarr > 10)
mask

array([ True, False, False,  True])

In [97]:
arr2d[mask]  # first and last rows

array([[ 1,  2,  3],
       [10, 11, 12]])

In [104]:
arr2dcopy = arr2d.copy()
arr2dcopy[arr2dcopy > 6] = 0  # set all values > 6 to 0
arr2dcopy

array([[1, 2, 3],
       [4, 5, 6],
       [0, 0, 0],
       [0, 0, 0]])

In [107]:
arr2dcopy = arr2d.copy()
arr2dcopy[(arr2dcopy < 3) | (arr2dcopy > 6)] = -1  
arr2dcopy

array([[-1, -1,  3],
       [ 4,  5,  6],
       [-1, -1, -1],
       [-1, -1, -1]])

**Global filtering with any and all**

In [108]:
arr = np.array([0,1,-5,2,9,0,3,-4,6])
print(arr.any())   

True


*0 is False, non-zero is True*

In [109]:
np.zeros(9).any()

False

In [110]:
arr.all()

False

In [111]:
np.ones(9).all()

True

---

#### Universal Function, or ufunc, is a function that performs element-wise operations on ndarrays.<br>Unary ufuncs work on a single ndarry, binary ufuncs work on a pair

---

#### <font color="brown">Some unary ufuncs</font>

In [112]:
arr = np.arange(1,6)
arr

array([1, 2, 3, 4, 5])

In [113]:
np.exp(arr)  # computes e^x for each x in arr

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [114]:
np.square(arr)

array([ 1,  4,  9, 16, 25])

In [115]:
np.sqrt(np.square(arr))

array([1., 2., 3., 4., 5.])

In [116]:
np.power(arr,3)

array([  1,   8,  27,  64, 125])

In [118]:
# same as
arr ** 3

array([  1,   8,  27,  64, 125])

In [119]:
arr2 = np.arange(-3,4)
arr2

array([-3, -2, -1,  0,  1,  2,  3])

In [120]:
np.abs(arr2)

array([3, 2, 1, 0, 1, 2, 3])

In [121]:
np.fabs(arr2)  # same, but gives real numbers, faster than abs

array([3., 2., 1., 0., 1., 2., 3.])

In [123]:
np.fabs(arr2).astype(int)

array([3, 2, 1, 0, 1, 2, 3])

In [126]:
arr2d = np.arange(1,10).reshape(3,3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [127]:
np.square(arr2d)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [128]:
np.power(arr2d,2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [129]:
arr2d   # does not change original array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [130]:
# ceil, floor, round to nearest integer
arr = np.exp(np.arange(1,6))
print(arr)
print(np.ceil(arr))
print(np.floor(arr))
print(np.rint(arr))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[  3.   8.  21.  55. 149.]
[  2.   7.  20.  54. 148.]
[  3.   7.  20.  55. 148.]


In [131]:
# is nan
arr = np.array([1,2,4,5]) 
print(np.isnan(arr))

[False False False False]


In [132]:
# np.nan gives NaN
arr = np.array([1,2,np.nan,4,5])  # NaN is value used to denote not available, or null
print(np.isnan(arr))

[False False  True False False]


---

#### <font color='brown'>Some binary ufuncs</font>

In [145]:
# raise elements of first array to elements of second array
arr1 = [1,2,3,4]
arr2 = [2,1,2,3]
np.power(arr1,arr2)

array([ 1,  2,  9, 64])

In [146]:
powers = np.ones((3,3));
powers[0] = powers[0]*2
powers[2] = powers[2]*3
powers

array([[2., 2., 2.],
       [1., 1., 1.],
       [3., 3., 3.]])

In [147]:
powers = powers.astype(int)
powers

array([[2, 2, 2],
       [1, 1, 1],
       [3, 3, 3]])

In [148]:
arr2d = np.arange(1,10).reshape(3,3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [149]:
np.power(arr2d,powers)

array([[  1,   4,   9],
       [  4,   5,   6],
       [343, 512, 729]])

In [154]:
# element-wise maximum
print(arr1)
print(arr2)
np.maximum(arr1,arr2)

[1, 2, 3, 4]
[2, 1, 2, 3]


array([2, 2, 3, 4])

In [155]:
arr = np.array([1,2,np.nan,4,5])
print(arr)
arr3 = [3,5,1,15,7]
print(arr3)

[ 1.  2. nan  4.  5.]
[3, 5, 1, 15, 7]


In [156]:
np.maximum(arr3,arr)

array([ 3.,  5., nan, 15.,  7.])

**Above shows that if either of the numbers is NaN, max is NaN**

In [157]:
np.max(arr3,arr)  # max is not binary unfunc

TypeError: only integer scalar arrays can be converted to a scalar index

In [159]:
np.max(arr3,2)  # try with scalar second parameter

AxisError: axis 2 is out of bounds for array of dimension 1

**From the error message 'AxisError ...' it appears that the scalar argument is the "axis" or dimension number.<br> To be continued.**