In [1]:
import re

In [55]:
res = re.match('[a-zA-z][_a-zA-Z0-9]*','_hello')
print(res) if res else print('no match')
print(res.group())

<re.Match object; span=(0, 6), match='_hello'>
_hello


In [111]:
res = re.findall('\s*"(.+)",((19|20)[0-9]{2}),(\$[0-9]{1,2}.[0-9]{2})\s*', '"Girl, Interrupted",2094,$11.99')
print(res) if res else print('no match')

[('Girl, Interrupted', '2094', '20', '$11.99')]


In [142]:
res = re.match('(\S)\s*(\S)\s*\S\s*\2\s*\1','albla')
print(res) if res else print('no match')

no match


In [143]:
import numpy as np

In [160]:
nparr = np.array([0,1,2,3,4,5,6,7,8,9])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [161]:
odd_vals = (nparr%2 == 1)
nparr[odd_vals] = nparr**2
nparr

ValueError: NumPy boolean array indexing assignment cannot assign 10 input values to the 5 output values where the mask is true

In [166]:
narr = np.arange(1,10).reshape(3,3)
narr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [193]:
res = re.match('([0-9]+|[0-9]*.[0-9]+)(e|E)[1-9][0-9]*$','0e1')
print(res) if res else print('no match')

<re.Match object; span=(0, 3), match='0e1'>


In [194]:
import numpy as np

In [199]:
arr = np.array([4,5,np.nan,9]) 
arr

array([ 4.,  5., nan,  9.])

In [214]:
nparr = np.arange(1,9)
npnew = nparr.copy()
npnew
new = npnew[(npnew % 2 == 1)]**2
new

array([ 1,  9, 25, 49])